### PR TITLE
Migrate from Travis to GitHub CI

### PR DESCRIPTION
**Pull request by MarijnS95**
The setup is far more verbose but has friendly names for every job and step, and GitHub provides better integration in the UI.

### CODE REVIEW

**Comment by MarijnS95** [comment]
For "efficiency" we can also merge all jobs, that saves a bunch of duplicated setup and allows all `step`s to use intermediate `target/` (and `~/.cargo/`, but we can also cache that) results since everything then runs sequentially on the same VM.

Downside is that you won't have a nice overview of what failed in a PR (fmt, checks, clippy or docs).

**Comment by MarijnS95** [comment]
Here's an example of one of these runs on my fork: https://github.com/MarijnS95/libv4l-rs/actions/runs/1869058275

It completes in about 3 minutes instead of [the 14 it took on the `next` branch by Travis](https://github.com/raymanfx/libv4l-rs/runs/5246748709). That's a significant improvement yet we can probably do even better [by caching](https://github.com/actions/cache/blob/main/examples.md#rust---cargo).

**Comment by raymanfx** [comment]
Please review these changes and let me know whether this is good to go from your side.

**Comment by MarijnS95** [comment]
@raymanfx I think so yes, just surprised that this `clippy::useless_conversion` suddenly shows up as I hadn't seen it before.

**Comment by MarijnS95** [comment]
Probably because I've not tested with `libv4l` locally and all the clippy spam from bindgen obscured it on the CI. You have my go-ahead :)

**Pull request merged**
