### PR TITLE
Allow setting of bytesused through Meta struct.

### LINKED ISSUE #30: Cannot set bytesused using meta struct when queueing data.
Hi,

I'm not sure if this is me misunderstanding something but when I fill the mmap output buffer with data I do not see a way to set the bytesUsed. Im streaming mjpeg and depending of the encoding the data size changes. As far as I can see now always the max buffer size is set. I tried using the meta struct to set `meta.bytesused` but that does not seem to be used in the library. As a workaround i did this in `src/io/mmap/stream.rs`:
```
diff --git a/src/io/mmap/stream.rs b/src/io/mmap/stream.rs
index 8a30846..13b21fc 100644
--- a/src/io/mmap/stream.rs
+++ b/src/io/mmap/stream.rs
@@ -190,9 +190,7 @@ impl<'a, 'b> OutputStream<'b> for Stream<'a> {
             v4l2_buf.type_ = self.buf_type as u32;
             v4l2_buf.memory = Memory::Mmap as u32;
             v4l2_buf.index = index as u32;
-            // output settings
-            let bytes = self.arena.get_unchecked_mut(index);
-            v4l2_buf.bytesused = bytes.len() as u32;
+            v4l2_buf.bytesused = self.buf_meta[index].bytesused;
             v4l2_buf.field = self.buf_meta[index].field;

             v4l2::ioctl(
```

However I do not know if this breaks other usage of the OutputStream. Am I missing something? Or am I on the right track and should my change be expanded to cover all situations.

Thanks in advance!

### PR DESCRIPTION
**Pull request by reyapo**
Fixes #30

### CODE REVIEW

**Comment by raymanfx** [comment]
I think we need some kind of safeguard here. If `self.buf_meta[index].bytesused` is not set, I would like to retain the old behavior.

**Comment by reyapo** [comment]
Indeed, would it make sense to make the meta.bytesused an `Option`?

**Comment by raymanfx** [comment]
The `Default::default()` impl for the `Metadata` struct (https://github.com/raymanfx/libv4l-rs/blob/master/src/buffer.rs#L102) will zero that field. So it's fine to check for a value of `0` and then just fallback to the existing logic.

**Comment by reyapo** [comment]
If I read the v4l2 (documentation)[https://www.kernel.org/doc/html/v4.15/media/uapi/v4l/buffer.html#struct-v4l2-plane], if bytesused is set to 0, for an output stream, the value is set to the size of the plane. So would it then not mean that the current implementation would work?

**Comment by raymanfx** [comment]
Ah, good find. Yes, I think you're right. However, that behavior seems counter-intuitive to me. Would you mind adding a comment to that portion of the code referencing the v4l2 docs and hinting at this specific fallback behavior?

**Pull request merged**
