### PR TITLE
Read returned index from DQBUF ioctl as OutputStream.

### LINKED ISSUE #29: Dequeue does not read buffer index in OutputStream
Hi,

I'm using your library to configure a Raspberry Pi as Output device and have run into an issue when trying to stream. 
It seems that there is a line missing in `src/io/mmap/stream.rs:218` that reads the returned index from the DQBUF ioctl.

In the CaptureStream you do this:
```
fn dequeue(&mut self) -> io::Result<usize> {
        let mut v4l2_buf: v4l2_buffer;
        unsafe {
            v4l2_buf = mem::zeroed();
            v4l2_buf.type_ = self.buf_type as u32;
            v4l2_buf.memory = Memory::Mmap as u32;
            v4l2::ioctl(
                self.handle.fd(),
                v4l2::vidioc::VIDIOC_DQBUF,
                &mut v4l2_buf as *mut _ as *mut std::os::raw::c_void,
            )?;
        }
        self.arena_index = v4l2_buf.index as usize;

        self.buf_meta[self.arena_index] = Metadata {
            bytesused: v4l2_buf.bytesused,
            flags: v4l2_buf.flags.into(),
            field: v4l2_buf.field,
            timestamp: v4l2_buf.timestamp.into(),
            sequence: v4l2_buf.sequence,
        };

        Ok(self.arena_index)
    }
```
However in the OutputStream implementation the line `self.arena_index = v4l2_buf.index as usize;` is missing.
When I added that line all started working.

Please let me know if you need any more info or if I'm doing something wrong.

Thanks!

### PR DESCRIPTION
**Pull request by reyapo**
Fixes #29

### CODE REVIEW

**Comment by raymanfx** [comment]
Could you remove the two commits from this branch? You can discard them using `git reset --hard HEAD^2`. Then force push the branch to your repo and this PR should update automatically.
Also, you can fix the original commit to make the CI pipeline happy by running `cargo fmt --all`, then `git add <FILE>` and finally `git commit --amend` to edit the commit.

**Comment by raymanfx** [comment]
If that's a problem for whatever reason, just let me know and I'll squash this PR as a single commit on my side.

**Comment by reyapo** [comment]
It should be done, `cargo fmt -all` does nothing on this commit, so the CI should not be failing? It looks like it uses another commit as it fails on the removed one. Or is there something else still?

**Comment by raymanfx** [comment]
Looks like there's some funny business going on with Travis CI and GitHub pull requests: https://github.com/travis-ci/travis-ci/issues/10210. I re-ran the job in Travis and it seems to work now.

**Pull request merged**
