### PR TITLE
Fix format descriptions

### LINKED ISSUE #5: Parsing of `v4l::format::Description.description` is incorrect
Formats with names such as `YUYV 4:2:2` appear as `"YUYV 4:2:2\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}UYV"`instead. I think this is because the parsing is not stopping at the first nul byte.

### PR DESCRIPTION
**Pull request by laptou**
Resolves #5. Descriptions will now stop at the first nul byte.

### CODE REVIEW

**Comment by raymanfx** [comment]
Hi, thanks for the PR!
May I ask what platform you are on? I.e. OS, distribution (in case of Linux), etc?
I'll have a look at this tomorrow.

**Comment by laptou** [comment]
> Hi, thanks for the PR!
> May I ask what platform you are on? I.e. OS, distribution (in case of Linux), etc?
> I'll have a look at this tomorrow.

Happy to help. I'm on Manjaro Linux, kernel version 5.7.9.

**Comment by raymanfx** [comment]
I commented on #5. Should there be something wrong with the code, I believe it should be possible to fix it without resorting to unsafe blocks.

**Comment by raymanfx** [comment]
Closing due to inactivity and lack of reproducibility.

**Pull request closed without merging**
