### PR TITLE
api: Update doc link for request codes.

### PR DESCRIPTION
**Pull request by wathiede**
I'm not sure if this is the right link, but the current link is broken as seen on https://docs.rs/v4l/latest/v4l/v4l2/api/fn.ioctl.html

### CODE REVIEW

**Comment by MarijnS95** [comment]
Theoretically the CI should run a `RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps --workspace --document-private-items` step to catch all broken links.

> I'm not sure if this is the right link

Notice that the `v4l` module isn't in scope, so this new link is wrong too:

```rust
error: unresolved link to `v4l::ioctl::codes`
   --> src/v4l2/api.rs:156:14
    |
156 | /// [codes]: v4l::ioctl::codes
    |              ^^^^^^^^^^^^^^^^^ no item named `v4l` in scope
```

The right link is straight to the ``[`vidioc`]`` module. There are many more violations so I fixed them all in #49 and added a job to the CI to disallow broken docs (and links) in the future :)

**Comment by wathiede** [comment]
Wow, that's a much better cleanup.  Thanks! And sorry for creating more work for you.

**Comment by MarijnS95** [comment]
@wathiede No worries, I just have an itch for cleaning up random repositories (there's a lot to do here, all the clippy lints, oh my!) and educating others on the topic! I hope I've been able to teach you how to build-test documentation for the next broken link that you encounter :grin:

**Comment by raymanfx** [comment]
Thank you for your efforts! Is this patch obsoleted by the now-merged other PR: https://github.com/raymanfx/libv4l-rs/pull/49? In that case, feel free to close this one.

**Pull request closed without merging**
