### PR TITLE
Update bindgen version in sys

### PR DESCRIPTION
**Pull request by lex148**
Great work with this crate! 

Would you be willing to open up your dependencies a little bit? I want to build this crate in a project with opencv. currently  they aren't compatible with you because of the version of bindgen you are using.

### CODE REVIEW

**Comment by raymanfx** [comment]
Hi, thanks for your contribution!
I'm not depending on a fixed bindgen version. I'll test your changes tomorrow and get them merged barring any unexpected issues.

Regarding the example - the commit failed to pass CI, could you please check whether that's something you can fix?

**Comment by lex148** [comment]
My bad, The example was just me playing around. It was not intended to be part of the PR

**Comment by raymanfx** [comment]
I see. Could you please trim down this PR to just the bindgen commit so I can merge it?

**Comment by dflemstr** [comment]
I added a PR offering a more direct approach in #12! It avoids using version ranges that might need to build breakage... not sure which approach is better!

**Comment by raymanfx** [comment]
Thank you @dflemstr!

Let's go with the less invasive solution for now. I thought about the methodology during the last days and came to the conclusion that I'd rather have a fixed version because bindgen updates may break the compilation at any time.

Feel free to re-open this issue in case of remaining issues!

**Pull request closed without merging**
