### PR TITLE
Add support for output devices

### PR DESCRIPTION
**Pull request by nvarner**
I created a new struct to represent output devices and new structs and enums to configure them. I also changed the examples so each one has an output counterpart (where that made sense) and wrote a simple example that forwards a capture device to an output device.

### CODE REVIEW

**Comment by raymanfx** [comment]
Thank you!
In order for me to review these changes and get them in eventually, could you please auto-format each individual commit and re-upload? I'd like to avoid changes like "Fix formatting" to keep the git history pristine.

Are you testing this using a real output device or something like the `v4l2loopback` kernel module? I don't have access to the former, so can only test using the latter myself.

**Comment by nvarner** [comment]
I'll go format each commit.

I have been testing this using `v4l2loopback`.

**Comment by raymanfx** [comment]
I put up a WIP branch here: https://github.com/raymanfx/libv4l-rs/commits/output. I basically reworked some of your commits (and fixed the formatting), added some comments and changed various variable names, but functionally it should be equivalent.
Could you please test that branch and let me know what you think?

**Comment by nvarner** [comment]
I just tested it with `v4l2loopback` and it worked as expected. Your changes look good to me.

**Comment by raymanfx** [comment]
I tested it using `v4l2loopback` on Fedora 32 today, works fine.
Merged and released as part of 0.10.0.

**Pull request closed without merging**
